services:
  app-dev:
    build:
      context: ../../..
      dockerfile: apps/app/docker/Dockerfile.dev
    container_name: app-dev
    restart: always
    ports:
      - "5100:5100"
    volumes:
      - ../../..:/mono
      - /mono/node_modules
    env_file:
      - ../.env
    environment:
      - NODE_ENV=development
