services:
  app-dev:
    build:
      context: ../../..
      dockerfile: apps/app/docker/Dockerfile.dev
    container_name: app-dev
    restart: always
    ports:
      - '5100:5100'
    volumes:
      - ../:/app
      - /app/node_modules
