services:
  app-production:
    build:
      context: .
      dockerfile: apps/app/docker/Dockerfile.prod
      args:
        APP_URL: ${APP_URL}
        AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
        AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
        AUTH_SECRET: ${AUTH_SECRET}
        FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
        FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
        FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
        NODE_ENV: ${NODE_ENV}
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
        STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
        WEBSITE_URL: ${WEBSITE_URL}
    environment:
      APP_URL: ${APP_URL}
      AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
      AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
      AUTH_SECRET: ${AUTH_SECRET}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      NODE_ENV: ${NODE_ENV}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      WEBSITE_URL: ${WEBSITE_URL}
    container_name: app-production
    restart: always
    ports:
      - "5101:3000"
