FROM node:22-bullseye

# Install turborepo globally with npm
RUN npm install turbo --global

# Create and switch to /mono directory
WORKDIR /mono

# Copy over the entire monorepo
COPY . .

# Install dependencies
RUN yarn install --frozen-lockfile

# Expose the port
EXPOSE 5100

# Start just the app
CMD ["yarn", "app", "dev"]
