FROM node:22-bullseye

# Install turborepo globally with npm
RUN npm install turbo --global

# Create and switch to /mono directory
WORKDIR /mono

# Copy over the rest of the files
COPY . .

RUN yarn install --frozen-lockfile

# Build the app
RUN yarn build

# Expose the port
EXPOSE 5100

# Start the website
CMD ["yarn", "web", "preview"]
