services:
  web-production:
    build:
      context: .
      dockerfile: apps/web/docker/Dockerfile.prod
      args:
        APP_URL: ${APP_URL}
        ENVIRONMENT: ${ENVIRONMENT}
        FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
        FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
        FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
        STORYBLOK_ACCESS_TOKEN: ${STORYBLOK_ACCESS_TOKEN}
        WEBSITE_URL: ${WEBSITE_URL}
    environment:
      APP_URL: ${APP_URL}
      ENVIRONMENT: ${ENVIRONMENT}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      STORYBLOK_ACCESS_TOKEN: ${STORYBLOK_ACCESS_TOKEN}
      WEBSITE_URL: ${WEBSITE_URL}
    container_name: web-production
    restart: always
    ports:
      - "5101:5101"
