services:
  web-dev:
    build:
      context: ../../..
      dockerfile: apps/web/docker/Dockerfile.dev
    container_name: web-dev
    restart: always
    ports:
      - '5101:5101'
    volumes:
      - ../:/app
      - /app/node_modules
